// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelAreasUygulama.Models;

#nullable disable

namespace PersonelAreasUygulama.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PersonelAreasUygulama.Models.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumGunu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonelId");

                    b.ToTable("Personels");

                    b.HasData(
                        new
                        {
                            PersonelId = 1,
                            Ad = "William",
                            DogumGunu = new DateTime(2023, 3, 28, 12, 7, 1, 999, DateTimeKind.Local).AddTicks(1584),
                            Email = "HotShakes@gmail.com",
                            Maas = 50m,
                            Soyad = "Shakespeare"
                        },
                        new
                        {
                            PersonelId = 2,
                            Ad = "Oguzhan",
                            DogumGunu = new DateTime(2023, 3, 28, 12, 7, 1, 999, DateTimeKind.Local).AddTicks(1622),
                            Email = "ogzhnylmz95@gmail.com",
                            Maas = 100m,
                            Soyad = "Yilmaz"
                        },
                        new
                        {
                            PersonelId = 3,
                            Ad = "Cansu",
                            DogumGunu = new DateTime(2023, 3, 28, 12, 7, 1, 999, DateTimeKind.Local).AddTicks(1623),
                            Email = "Cansu91@gmail.com",
                            Maas = 150m,
                            Soyad = "Yilmaz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
